### ISSUE TITLE
HS sur tes icones de la barre horizontale

### ISSUE THREAD

**Issue by jybi89** [Bastiencc/french-radio-media-player#1]
Salut Bastien, merci pour cette integration, je l'utilise depuis plus d'un an, c'est génial !

je voulais savoir comment as tu coloré tes icones de la barre horizontale ? oui petit hors sujet qui n'a rien à voir avec la radio :)

merci d'avance pour ta réponse :)  si tu passes sur le forum HACF.fr n'hesite pas à faire un coucou ^^

Hi Bastien, thank you for this integration, I have been using it for over a year, it's great!

I wanted to know how you colored your icons of the horizontal bar? yes little off topic that has nothing to do with radio :)

thank you in advance for your answer :) if you pass on the HACF.fr forum do not hesitate to say hello ^^

**Comment by Bastiencc** [comment]
Salut !

Content que l'intégration soit utile ! ça fait plaisir.
Concernant les icônes, j'utilise une extension : https://github.com/maykar/custom-header
Elle continue de fonctionner mais n'est plus maintenue.

A+
Bastien

**Comment by jybi89** [comment]
elle est beaucoup utilisée, je vois revenir regulierement des questions concernant ton integration sur les differents discord et forums ;)
en effet cchui ! on l'avait oublié celui là ;) merci pour ta réponse rapide 👍

**Comment by Bastiencc** [comment]
Tant mieux alors , ça fait plaisir ! 
Je ne suis plus beaucoup sur les forums et cie donc je ne m'en rend pas compte.
